language: generic

go:
  - 1.12.x

matrix:
  include:
    - os: linux
      dist: bionic

services:
  - docker

script:
  - . ./ci/build.sh
  - pwd
  - ls -latr

# note before_deploy will run before each deploy provider
before_deploy:
  - . ./ci/release.sh

deploy:
  provider: releases
  skip_cleanup: true
  api_key: $GITHUB_TOKEN
  file: ci/release/*
  file_glob: true
  on:
    tags: true
    repo: appsody/stacks
    branch: master
